### Obtener todos los viajes
GET http://localhost:3000/api/viajes

###

### Obtener un viaje por ID
GET http://localhost:3000/api/viajes/1


### Crear un nuevo viaje
POST http://localhost:3000/api/viajes
Content-Type: application/json

{
  "fechaSalida": "2024-01-15",
  "fechaLlegada": "2024-01-25",
  "estado": "Pendiente",
  "cupos": 5,
  "costoEstimado": 1500.00,
  "cupoDisponible": 3,
  "total": 7500.00,
  "totalPorPersona": 1500.00,
  "descVehiculo": "Toyota Corolla",
  "idOrganizador": 1,
  "idCiudad": 2,
  "categorias": [2]
}

###

### Actualizar un viaje existente (completo)
PUT http://localhost:3000/api/viajes/2
Content-Type: application/json

{
  "fechaSalida": "2025-11-10T10:00:00.000Z",
  "fechaLlegada": "2025-11-10T18:30:00.000Z",
  "estado": "Disponible",
  "cupos": 10,
  "costoEstimado": 18000,
  "descVehiculo": "Peugeot 208 azul",
  "ciudad": 1,
  "organizador": 3,
  "categorias": [1]
  
}

###

### Actualizar parcialmente un viaje
PATCH http://localhost:3000/api/viajes/1
Content-Type: application/json

{
  "estado": "disponible"
  
}

###

### Eliminar un viaje
DELETE http://localhost:3000/api/viajes/21

###
GET http://localhost:3000/api/viajes/categorias/1
