### Obtener una lista de solictudes
GET http://localhost:3000/api/solicitudes

### Obtener uns solicitud por id
GET http://localhost:3000/api/solicitudes/3/1

### Crear una nueva solicitud
POST http://localhost:3000/api/solicitudes/
Content-Type: application/json

{
  "idPasajero": 3,
  "idViaje": 1,
  "estado": "Aceptada",
  "fechaSolicitud": "2026-02-10"

}


### Modificar una solicitud(PUT/PATCH)
### PUT --> debe ser idempotente, si se ejecuta varias veces el resultado debe ser el mismo
### Se usa para modificaciones completas
### Para poder ser idempotente se deben enviar todos los elementos que pueden ser modificados
### PATCH --> puede ser idempotente pero no es un requisito
### Se usa para modificaciones parciales, solo algunos atributos

PUT http://localhost:3000/api/solicitudes/2/1
Content-Type: application/json

{
  "estado": "Aceptada",
  "fechaSolicitud": "2025-10-16"
}


### Modificar algunos datos de una solicitud
PATCH http://localhost:3000/api/solicitudes/5/5
Content-Type: application/json

{
  "estado": "Cancelada"
}

### Borrar una solicitud
DELETE http://localhost:3000/api/solicitudes/3/1