### Obtener una lista de pasajeros
GET http://localhost:3000/api/pasajeros

### Obtener un pasajero por id
@id = {{ createPasajero.response.body.data.id }}
GET http://localhost:3000/api/pasajeros/{{id}}

### Crear un nuevo pasajero
@ name createPasajero
POST http://localhost:3000/api/pasajeros
Content-Type: application/json

{
  "nombre": "Jorgelina",
  "apellido": "Lannutti",
  "telefono": "341345656",
  "direccion": "Rivadavia 234",
  "email": "jorgelina@gmail.com"
}


### Modificar un pasajero(PUT/PATCH)
### PUT --> debe ser idempotente, si se ejecuta varias veces el resultado debe ser el mismo
### Se usa para modificaciones completas
### Para poder ser idempotente se deben enviar todos los elementos que pueden ser modificados
### PATCH --> puede ser idempotente pero no es un requisito
### Se usa para modificaciones parciales, solo algunos atributos

PUT http://localhost:3000/api/pasajeros/{{id}}
Content-Type: application/json

{
  "nombre": "Eugenia",
  "apellido": "Abonizio",
  "telefono": "3402549638",
  "direccion": "San Nicolas 207 bis",
  "email": "abril@gmail"
}


### Modificar algunos datos de un pasajero
###PATCH http://localhost:3000/api/pasajeros/1
###Content-Type: application/json

###{
 ###"nombre": "Abril",
  ###"direccion": "Rivadavia 234",
  ###"email": "abril.abonizio@gmail"
###}

### Borrar un pasajero
DELETE http://localhost:3000/api/pasajeros/1
